
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
  
  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
  
  - job_name: kafka
    static_configs:
      - targets: ['kafka:7071']